# Generated by Django 2.0 on 2018-12-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='year_in_school',
            new_name='build',
        ),
    ]
