# Generated by Django 2.0 on 2018-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181224_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='misc',
        ),
        migrations.AlterField(
            model_name='post',
            name='build',
            field=models.CharField(choices=[('AMD', 'amd'), ('INTEL', 'intel')], default='INTEL', max_length=2),
        ),
    ]
