# Generated by Django 2.0 on 2018-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181224_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amd_cpu',
            field=models.CharField(choices=[('R3-1', 'Ryzen 3 series 1'), ('R3-2', 'Ryzen 3 series 2'), ('R5-1', 'Ryzen 5 series 1'), ('R5-2', 'Ryzen 5 series 2'), ('R7-1', 'Ryzen 7 series 1'), ('R7-2', 'Ryzen 7 series 2'), ('TR-1', 'Ryzen Threadripper series 1'), ('TR-2', 'Ryzen Threadripper series 2')], default='R5-2', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='build',
            field=models.CharField(choices=[('AMD', 'AMD'), ('INTEL', 'INTEL')], default='INTEL', max_length=2),
        ),
    ]
