# Generated by Django 2.0 on 2018-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181224_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amd_cpu',
            field=models.CharField(choices=[('R3-1', 'Ryzen 3 Gen-1'), ('R3-2', 'Ryzen 3 Gen-2'), ('R5-1', 'Ryzen 5 Gen-1'), ('R5-2', 'Ryzen 5 Gen-2'), ('R7-1', 'Ryzen 7 Gen-1'), ('R7-2', 'Ryzen 7 Gen-2'), ('TR-1', 'Ryzen Threadripper Gen-1'), ('TR-2', 'Ryzen Threadripper Gen-2')], default='R5-2', max_length=2),
        ),
    ]
