# Generated by Django 2.0 on 2018-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181224_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gpu',
            field=models.CharField(choices=[('GTX-1060', 'Nvidia GTX 1060'), ('GTX-1060Ti', 'Nvidia GTX 1060Ti'), ('GTX-1070', 'Nvidia GTX 1070'), ('GTX-1070Ti', 'Nvidia GTX 1070Ti'), ('GTX-1080', 'Nvidia GTX 1080'), ('GTX-1080Ti', 'Nvidia GTX 1080Ti'), ('GTX-2070', 'Nvidia GTX 2070'), ('GTX-2070ti', 'Nvidia GTX 2070Ti'), ('GTX-2080', 'Nvidia GTX 2080'), ('GTX-2080Ti', 'Nvidia GTX 2080Ti')], default='GTX-1080', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='intel_cpu',
            field=models.CharField(choices=[('i3-7', 'i3 Gen-7'), ('i3-8', 'i3 Gen-8'), ('i5-7', 'i5 Gen-7'), ('i5-8', 'i5 Gen-8'), ('i7-7', 'i7 Gen-7'), ('i7-8', 'i7 Gen-8'), ('i9-7', 'i9 Gen-7'), ('i9-8', 'i9 Gen-8')], default='i5-8', max_length=2),
        ),
    ]
