# Generated by Django 2.0 on 2018-12-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='misc',
            field=models.TextField(blank=True),
        ),
    ]
