# Generated by Django 2.0 on 2018-12-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181224_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amd_cpu',
            new_name='cpu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intel_cpu',
        ),
    ]
