# Generated by Django 2.0 on 2018-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181224_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='build',
        ),
        migrations.AlterField(
            model_name='post',
            name='cpu',
            field=models.CharField(choices=[('i3-7', 'i3 Gen-7'), ('i3-8', 'i3 Gen-8'), ('i5-7', 'i5 Gen-7'), ('i5-8', 'i5 Gen-8'), ('i7-7', 'i7 Gen-7'), ('i7-8', 'i7 Gen-8'), ('i9-7', 'i9 Gen-7'), ('i9-8', 'i9 Gen-8'), ('R3-1', 'Ryzen 3 Gen-1'), ('R3-2', 'Ryzen 3 Gen-2'), ('R5-1', 'Ryzen 5 Gen-1'), ('R5-2', 'Ryzen 5 Gen-2'), ('R7-1', 'Ryzen 7 Gen-1'), ('R7-2', 'Ryzen 7 Gen-2'), ('TR-1', 'Ryzen Threadripper Gen-1'), ('TR-2', 'Ryzen Threadripper Gen-2')], default='i5-8', max_length=2),
        ),
    ]
