# Generated by Django 2.0 on 2018-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20181224_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='misc',
            new_name='config',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
