# Generated by Django 2.0 on 2018-12-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20181224_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='config',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='mainboard',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_storage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='psu',
            field=models.CharField(choices=[('400W', '400W'), ('450W', '450W'), ('500W', '500W'), ('550W', '550W'), ('600W', '600W'), ('650W', '650W'), ('700W', '700W'), ('750W', '750W'), ('800W', '800W'), ('850W', '850W'), ('1000W', '1000W')], default='750W', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='ram',
            field=models.CharField(choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], default='8GB', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_storage',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
