# Generated by Django 2.0 on 2018-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20181224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cpu',
            field=models.CharField(choices=[('i3-7', 'i3 Gen-7'), ('i3-8', 'i3 Gen-8'), ('i5-7', 'i5 Gen-7'), ('i5-8', 'i5 Gen-8'), ('i7-7', 'i7 Gen-7'), ('i7-8', 'i7 Gen-8'), ('i9-7', 'i9 Gen-7'), ('i9-8', 'i9 Gen-8'), ('R3-1', 'Ryzen 3 Gen-1'), ('R3-2', 'Ryzen 3 Gen-2'), ('R5-1', 'Ryzen 5 Gen-1'), ('R5-2', 'Ryzen 5 Gen-2'), ('R7-1', 'Ryzen 7 Gen-1'), ('R7-2', 'Ryzen 7 Gen-2'), ('TR-1', 'Ryzen Threadripper Gen-1'), ('TR-2', 'Ryzen Threadripper Gen-2')], default='i5-8', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='gpu',
            field=models.CharField(choices=[('GTX-1060', 'Nvidia GTX 1060'), ('GTX-1060Ti', 'Nvidia GTX 1060Ti'), ('GTX-1070', 'Nvidia GTX 1070'), ('GTX-1070Ti', 'Nvidia GTX 1070Ti'), ('GTX-1080', 'Nvidia GTX 1080'), ('GTX-1080Ti', 'Nvidia GTX 1080Ti'), ('GTX-2070', 'Nvidia GTX 2070'), ('GTX-2070ti', 'Nvidia GTX 2070Ti'), ('GTX-2080', 'Nvidia GTX 2080'), ('GTX-2080Ti', 'Nvidia GTX 2080Ti')], default='GTX-1080', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='psu',
            field=models.CharField(choices=[('400W', '400W'), ('450W', '450W'), ('500W', '500W'), ('550W', '550W'), ('600W', '600W'), ('650W', '650W'), ('700W', '700W'), ('750W', '750W'), ('800W', '800W'), ('850W', '850W'), ('1000W', '1000W')], default='750W', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='ram',
            field=models.CharField(choices=[('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], default='8GB', max_length=20),
        ),
    ]
