# Generated by Django 2.0 on 2018-12-25 17:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181225_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='defaults/default_profile_pic.png', force_format='PNG', keep_meta=True, quality=0, size=[250, 250], upload_to='profile_pics'),
        ),
    ]
