# Generated by Django 2.0 on 2019-01-11 21:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('cpu', models.CharField(choices=[('i3 Gen-7', 'i3 Gen-7'), ('i3 Gen-8', 'i3 Gen-8'), ('i5 Gen-7', 'i5 Gen-7'), ('i5 Gen-8', 'i5 Gen-8'), ('i7 Gen-7', 'i7 Gen-7'), ('i7 Gen-8', 'i7 Gen-8'), ('i9 Gen-7', 'i9 Gen-7'), ('i9 Gen-8', 'i9 Gen-8'), ('Ryzen 3 Gen-1', 'Ryzen 3 Gen-1'), ('Ryzen 3 Gen-2', 'Ryzen 3 Gen-2'), ('Ryzen 5 Gen-1', 'Ryzen 5 Gen-1'), ('Ryzen 5 Gen-2', 'Ryzen 5 Gen-2'), ('Ryzen 7 Gen-1', 'Ryzen 7 Gen-1'), ('Ryzen 7 Gen-2', 'Ryzen 7 Gen-2'), ('Ryzen Threadripper Gen-1', 'Ryzen Threadripper Gen-1'), ('Ryzen Threadripper Gen-2', 'Ryzen Threadripper Gen-2')], default='i5 Gen-8', max_length=30)),
                ('gpu', models.CharField(choices=[('GTX 1060', 'GTX 1060'), ('GTX 1060Ti', 'GTX 1060Ti'), ('GTX 1070', 'GTX 1070'), ('GTX 1070Ti', 'GTX 1070Ti'), ('GTX 1080', 'GTX 1080'), ('GTX 1080Ti', 'GTX 1080Ti'), ('GTX 2070', 'GTX 2070'), ('GTX 2070ti', 'GTX 2070Ti'), ('GTX 2080', 'GTX 2080'), ('GTX 2080Ti', 'GTX 2080Ti')], default='GTX 1080', max_length=30)),
                ('ram', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB')], default='8GB', max_length=30)),
                ('psu', models.CharField(choices=[('400W', '400W'), ('450W', '450W'), ('500W', '500W'), ('550W', '550W'), ('600W', '600W'), ('650W', '650W'), ('700W', '700W'), ('750W', '750W'), ('800W', '800W'), ('850W', '850W'), ('1000W', '1000W')], default='750W', max_length=30)),
                ('primary_storage', models.CharField(max_length=120)),
                ('secondary_storage', models.CharField(blank=True, max_length=120)),
                ('mainboard', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='defaults/default_rig_pic.png', force_format='PNG', keep_meta=True, quality=0, size=[500, 500], upload_to='posts_pics')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
