# Generated by Django 2.0 on 2018-12-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181225_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
