# Generated by Django 2.0 on 2018-12-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181225_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_info',
        ),
        migrations.AlterField(
            model_name='post',
            name='mainboard',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='secondary_storage',
            field=models.CharField(max_length=120),
        ),
    ]
