# Generated by Django 2.0 on 2018-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181226_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='primary_storage',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='secondary_storage',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
