# Generated by Django 2.0 on 2018-12-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_on',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='user',
        ),
    ]
