# Generated by Django 2.0 on 2018-12-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181226_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=False, max_length=500),
            preserve_default=False,
        ),
    ]
