# Generated by Django 2.0 on 2019-01-01 16:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='defaults/default_rig_pic.png', force_format='PNG', keep_meta=True, quality=0, size=[500, 500], upload_to='posts_pics'),
        ),
    ]
