# Generated by Django 2.0 on 2019-01-02 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5),
        ),
    ]
